### ISSUE TITLE
line contact support

### ISSUE THREAD

**Issue by xeonz1** [mayataka/robotoc#124]
will line contact be supported in the future?

**Comment by mayataka** [comment]
What do you mean by line contact?
Is it the contact in feet of Cassie robot?
If so, it will be possible after new Pinocchio feature is released and I update this repo for the new Pinocchio.
You then may be able to consider a line contact via couple of point contacts.

**Comment by mayataka** [comment]
The current code cannot consider line contact by doing so.
It is no wonder it the optimization fails. 
Even the optimizer converges, the solution may be meaningless.
This is because Pinocchio consider the external contact force as a corresponding joint force.
I’m not too sure, but the new Pinocchio feature can resolve it.

**Comment by mayataka** [comment]
Thank you for being interested in this repo.
